import type { GenerationType } from "./credits";

export type GenerationStatus = "processing" | "pending_review" | "rendering" | "done" | "error";

export type GenerationDoc = {
  userId: string;
  niche: string;
  /** Free-form description of what to create (Hebrew). */
  userRequest?: string | null;
  type: GenerationType;
  logoUrl?: string | null;
  status: GenerationStatus;
  /** Requested aspect ratio (used by Imagen/Veo workers). */
  aspectRatio?: "9:16" | "1:1" | "16:9" | string | null;
  sourceImageUrl?: string | null; // for remotion pipeline (input image) – single or first of list
  /** User-uploaded images (חומרי גלם). When set, Remotion can use multiple images (slideshow). Make receives these for Gemini Vision. */
  sourceImageUrls?: string[] | null;
  resultUrl?: string | null;
  /** When we post-process (e.g. Cloudinary watermark), keep original result for debugging. */
  rawResultUrl?: string | null;
  /** Debugging/prompts: generated by Gemini for Imagen and Veo. */
  imagePrompt?: string | null;
  videoPrompt?: string | null;
  caption?: string | null;
  hashtags?: string[] | null;
  overlayText?: string | null;
  createdAt: number; // Date.now()
  errorMessage?: string | null;
  /** Remotion: "default" | "pop" | "dramatic". If missing, worker picks random. Can come from Gemini via Make callback. */
  videoStyle?: string | null;
  /** Smart DJ: "energetic" | "calm" | "luxury" | "trendy". Worker gets track from Jamendo API. From Make callback. */
  audioVibe?: string | null;
  /** SFX URL from Make callback (e.g. module 5). Played when first *highlighted* word pops in Remotion. */
  sfxUrl?: string | null;

  /** Premium (Veo): internal progress stage + heartbeat for UI. */
  premiumStage?: "submitted" | "generating" | "finalizing" | "done" | string | null;
  premiumUpdatedAt?: number | null;

  /** Auto Upload: when set, this generation is linked to a scheduled post. */
  autoUpload?: {
    enabled?: boolean;
    requireApproval?: boolean;
    status?: "waiting_asset" | "pending_approval" | "approved" | "cancelled" | "publishing" | "done" | "rejected" | "error" | string;
    platform?: "instagram" | "facebook" | string;
    placement?: "post" | "reels" | "story" | string;
    scheduledPostId?: string | null;
  } | null;
};

/** Brand Kit – ערכת מותג (לוגו, צבע, טלפון, אתר). נשמר ב־users/{uid}/brandKit/settings. */
export type BrandKitDoc = {
  logoUrl?: string | null;
  primaryColor?: string | null; // hex, e.g. "#00f5ff"
  phone?: string | null;
  website?: string | null;
  updatedAt: number;
};

export type AutoUploadSettingsDoc = {
  enabled: boolean;
  requireApproval: boolean;
  niche: string;
  userRequestTemplate: string;
  postsPerDay: number;
  timeSlots: string[]; // ["09:00","13:00"]
  /** Optional per-slot override: { "09:00": "premium" } */
  slotTypes?: Partial<Record<string, GenerationType>>;
  timeZone: "Asia/Jerusalem";
  destinations: Array<{
    platform: "instagram" | "facebook";
    placement: "post" | "reels" | "story";
  }>;
  mix: {
    image: number;
    remotion: number;
    premium: number;
  };
  updatedAt: number;
};

